---
- name: Docker Register
  apt:
    name: docker.io
    state: latest
    update_cache: yes
  register: docker

- name: Docker py file
  pip:
    name: docker.py
    state: latest
  when: docker.changed

- name: Docker Image
  docker_image:
    name: docker.elastic.co/elasticsearch/elasticsearch:7.10.1

- name: Docker Network
  docker_network:
    name: elastic

- name: Docker Container
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    state: present
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - name: elastic

- name: Kibana Docker Image
  docker_image:
    name: docker.elastic.co/kibana/kibana:7.10.1

- name: Kibana Docker Container
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.1
    state: present
    ports:
      - "5601:5601"
    networks:
      - name: elastic

- name: Logstash Docker Image
  docker_image:
    name: docker.elastic.co/logstash/logstash:7.10.1

- name: Logstash Docker Container
  docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:7.10.1
    state: present
    ports:
      - "5044:5044"
    networks:
      - name: elastic

# tasks file for roles/ubuntuelstins
