---
- name: Pre-reqs for Elastic Stack
  yum:
    name: java-11-openjdk-devel
    state: latest
    update_cache: yes

- name: Elastic Search Repo Installation
  yum_repository:
    name: Elastic_7.X_repo
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    desc: Elastic 7.x repo

- name: Rpm key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Elastic Search Installation
  yum:
    name: elasticsearch
    state: latest
    update_cache: yes

- name: Network Host
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host'
    line: 'network.host: localhost'

- name: Http Port
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: 'http.port:'
    line: 'http.port: 9200'

- name: Elastic Search Start
  service:
    name: elasticsearch
    state: started
    update_cache: yes

- name: Logstash Installation
  yum:
    name: logstash
    state: latest
    update_cache: yes

- name: Http Host
  lineinfile:
    dest: /etc/logstash/logstash.yml
    regexp: 'http.host:'
    line: 'http.host: 127.0.0.1'

- name: Logstash Start
  service:
    name: logstash
    state: started
    update_cache: yes

- name: Kibana Installation
  yum:
    name: kibana
    state: latest
    update_cache: yes

- name: Server Host
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regexp: 'server.host'
    line: 'server.host: "0.0.0.0"'

- name: Server Port
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regexp: 'server.port:'
    line: 'server.port: 5601'

- name: Config File
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regexp: 'elasticsearch.hosts:'
    line: 'elasticsearch.hosts: ["http://localhost:9200"]'

- name: Kibana Start
  service: 
    name: kibana
    state: started
    update_cache: yes
# tasks file for roles/elasticstack2ins
